name: ASP.NET Build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-dotnet@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./aspnet-core-dotnet-core.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./aspnet-core-dotnet-core.sln --configuration Release

